### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by nasht00** [hschmidt/EnvPane#10]
Since this project was last edited in 2013, I am wondering, is it still alive?
Is the current version still relevant to Yosemite?

If the project is dead, can you recommend an alternate project?

**Comment by hschmidt** [comment]
> is it still alive?

Depends on your definition of "alive" in the context of a software project. It is not my highest priority to maintain it.

> Is the current version still relevant to Yosemite?

Yes. I use it on Yosemite and it works for me.

> If the project is dead, can you recommend an alternate project?

I don't thinks so.
