### ISSUE TITLE
Upgrade to El Capitan?

### ISSUE THREAD

**Issue by johnyradio** [hschmidt/EnvPane#14]
hi

on El Capitan, when i try to install, i get "Failed to write agent's launchd job description"."

![Alt text](http://www.pixhoster.info/f/2016-09/93bb4bdc340fbe366736bf244ab2f465.png)
http://www.pixhoster.info/f/2016-09/93bb4bdc340fbe366736bf244ab2f465.png

any plans to upgrade?

thx!

**Comment by hschmidt** [comment]
EnvPane works for me on El Capitan. Did you chose "Install this user only" when installing it? Are you an admin on your box?
