### ISSUE TITLE
EnvPane "failed to load/start agent"

### ISSUE THREAD

**Issue by UdomkarnART** [hschmidt/EnvPane#16]
Hi! I use OS X 10.12.2 Sierra and I found that after I click launch EnvPane on System Preferences it show " Failed to load/start agent" any solution?

**Comment by hschmidt** [comment]
Can you send the relevant logs from the Console app? Did you install for all users or current user only?

**Comment by UdomkarnART** [comment]
Hi! Thanks for reply. I set it as current users only, and I don't know much with command however if you tell me the steps to open logs from Console I may send you.

**Comment by hschmidt** [comment]
1) Hit Cmd-Space — type `Console` — Hit Enter — (Console app starts) — Click `system.log` on the left — Click Search bar on the top — type `Env`— Select all matching lines, copy, then paste here.

2) Try

https://github.com/hschmidt/EnvPane/releases/tag/releases%2F0.6.alpha1

**Comment by UdomkarnART** [comment]
You mean this?

Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.397
Jan  5 12:00:49 10 System Preferences[789]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  5 12:07:29 10 System Preferences[995]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}

**Comment by UdomkarnART** [comment]
This is full.

Jan  3 10:41:17 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.482
Jan  3 12:32:22 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.411
Jan  3 12:44:45 10 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100007.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.490
Jan  3 19:03:43 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.391
Jan  3 20:08:57 UDOMKARNs-MacBook-Pro System Preferences[1753]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:09:20 UDOMKARNs-MacBook-Pro System Preferences[1773]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:12:18 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.411
Jan  3 20:13:33 UDOMKARNs-MacBook-Pro System Preferences[655]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:20:02 10 System Preferences[942]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:20:24 10 System Preferences[951]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:21:18 10 System Preferences[999]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:25:56 UDOMKARNs-MacBook-Pro System Preferences[1146]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:28:11 10 System Preferences[1220]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:33:53 10 System Preferences[1333]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:39:33 UDOMKARNs-MacBook-Pro System Preferences[1437]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 20:44:43 10 System Preferences[1553]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  3 22:35:38 UDOMKARNs-MacBook-Pro System Preferences[3172]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  4 08:55:18 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.493
Jan  4 08:59:06 10 System Preferences[915]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  4 09:05:10 10 System Preferences[1053]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  4 09:18:56 10 System Preferences[1285]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  4 20:16:56 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.385
Jan  4 20:25:30 10 System Preferences[924]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  4 20:27:34 10 System Preferences[961]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  5 00:08:31 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.420
Jan  5 11:57:41 UDOMKARNs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller specified a plist with bad ownership/permissions: path = /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist, caller = otherbsd.397
Jan  5 12:00:49 10 System Preferences[789]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}
Jan  5 12:07:29 10 System Preferences[995]: Error: Error Domain=EnvLib Code=0 "Failed to load/start agent" UserInfo={NSLocalizedDescription=Failed to load/start agent}

**Comment by hschmidt** [comment]
Interesting. Can you please run 

```
umask ; ls -l /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist
```

in Terminal and post the output?

**Comment by hschmidt** [comment]
… and 

```
ls -l /Users/udomkarn/Library/LaunchAgents
```

**Comment by UdomkarnART** [comment]
It show this..

10:~ udomkarn$ umask ; ls -l /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist
0022
-rw----rw-  1 udomkarn  staff  719 Oct 25 13:23 /Users/udomkarn/Library/LaunchAgents/net.hannesschmidt.EnvAgent.plist
10:~ udomkarn$ 

And this.

10:~ udomkarn$ ls -l /Users/udomkarn/Library/LaunchAgents
total 40
-rw----rw-@ 1 udomkarn  staff  805 Sep 25 22:36 com.google.keystone.agent.plist
-rw----rw-  1 udomkarn  staff  668 Nov  5 00:13 com.redgiantsoftware.updater.plist
-rw----rw-  1 udomkarn  staff  482 Sep 25 21:26 com.spigot.ApplicationManager.plist
-rw----rw-  1 udomkarn  staff  424 Jan  5 22:39 com.vladalexa.MagicPrefs.plist
-rw----rw-  1 udomkarn  staff  719 Oct 25 13:23 net.hannesschmidt.EnvAgent.plist
10:~ udomkarn$

**Comment by hschmidt** [comment]
This makes sense now. Launchd is refusing to load the EnvAgent because the corresponding plist is world-writeable. There is nothing I can do about this. This is what it should look like (from my system):

```
-rw-r--r--  1 hannes  staff  713 Jan  4 18:12 net.hannesschmidt.EnvAgent.plist
```

So to fix this you should at least change the permission of the plist file, and probably also the directory containing it. 

Also, the presence of the `com.spigot.ApplicationManager.plist` file indicates that your system is or was infected with the Spigot malware which could explain why the permissions are out of whack. If I were you, I would take care of that ASAP.

https://www.google.com/search?q=%22com.spigot.ApplicationManager%22

Closing.

**Comment by UdomkarnART** [comment]
Thanks for your help! I change the permission on ~/Library/LaunchAgent and reinstalled and now it become working again.  Thanks you.
