### ISSUE TITLE
EnvPane recommended to fldigi on macOS users that require NLS support

### ISSUE THREAD

**Issue by HK4QWC** [hschmidt/EnvPane#20]
Hello @hschmidt:

This is just a quick note to let you know that I am recommending EnvPane to [fldigi](https://github.com/HK4QWC/fldigi-macOS-NLS)* on macOS users that require NLS support in their amateur radio operation.

Thanks for releasing EnvPane. It is a great solution for managing the environment variables in macOS.

Regards, 

Christian W. 
HK4QWC
* [Fldigi](https://sourceforge.net/projects/fldigi/) is a software modem for Amateur Radio use. It is a sound card based program that is used for both transmitting and receiving data in several modes using voice radio channels.

**Comment by hschmidt** [comment]
Thanks for the support 👍 .
