### ISSUE TITLE
32bits unsupported on Catalina

### ISSUE THREAD

**Issue by vcajes** [hschmidt/EnvPane#29]
What version of EnvPane are you using. Did you download the official release or
did you build it yourself?
Yes. v06

What version of OS X are you using (or attempting to use) EnvPane on?
Catalina

Did you install EnvPane for the current user only or for all users? I admit,
that's a bit of a trick question.
Current user

Did you install EnvPane as an administrative user?
No

Can you provide relevant system.log messages? You can use the Console
application to get those: Hit Cmd-Space, type `Console`, hit enter (the Console
app should open), click on `system.log` on the left, click the search bar at
the top and type `Env` to filter the list. Copy and paste it below but be sure
to redact any confidential informations such as account names, IP addresses etc.

The problem with Calatina is that it does not support anymore 32bit applications and we might need to re-compile this to support 64bits.

**Comment by junologue** [comment]
Come on, just make it 64bit compatible please! It's 2020 ;)

**Comment by hschmidt** [comment]
Should be fixed in 0.7
