### ISSUE TITLE
The variables are not set, even when I open a new terminal shell

### ISSUE THREAD

**Issue by CosminTango** [hschmidt/EnvPane#30]
Hello. I have downloaded EnvPane directly from git.
I am using MacOSX Catalina and of course, I have installed for my user only, as a normal user (not sudo).

I have set a variable in it, TEST_VAR and gave it a string value, "John Smith". I have opened a new terminal and echoed $TEST_VAR but it was empty. How exactly is this supposed to work, please?

**Comment by Garbee** [comment]
I noticed this the other day with iterm. I had to fully quit iterm and restart the process for the variables to be in place.

**Comment by CosminTango** [comment]
Sorry for answering so late. Hm. Still seems to be occuring...

**Comment by hschmidt** [comment]
https://github.com/hschmidt/EnvPane#why-arent-running-applications-affected
