### ISSUE TITLE
Not working with Big Sur

### ISSUE THREAD

**Issue by TheFruxz** [hschmidt/EnvPane#31]
I recently installed EnvPane as an Administrator directly from GitHub.

If I open the pane in the settings app, it only shows an empty, not for dark mode optimized Pane!

![Bildschirmfoto 2020-07-10 um 00 11 06](https://user-images.githubusercontent.com/28064149/87095854-daef4c80-c241-11ea-957f-490b70b9ae64.png)

**Comment by TheFruxz** [comment]
I figured out, that it won't work, if it is installed at every MacOS User

**Comment by wintersnyc** [comment]
Thanks for this clarification, extremely helpful in configuring EnvPane to work on 10.15 Catalina.

**Comment by myanmccann** [comment]
Exactly, I thought it was a 32-bit vs 64-bit problem on Catalina, but turns out it just cant be installed for every user, I just moved the .prefPane file from:

 /Library/PreferencePanes ---> /Users/{USERNAME}/Library/PreferencePanes 

all good now!

**Comment by mbaas2** [comment]
I'm trying to use it on BigSur. This suggestion has helped to avoid the empty pane and it now even shows existing vars. But after pressing + to add one, I can't type into the edit-field.

**Comment by hschmidt** [comment]
https://github.com/hschmidt/EnvPane/issues/31#issuecomment-788195691
