### ISSUE TITLE
Not working on MacOS 13.2.1

### ISSUE THREAD

**Issue by jonahclarsen** [hschmidt/EnvPane#36]
The pref pane is just blank. I have tried restarting my computer. 

<img width="876" alt="Screenshot 2023-06-02 at 12 38 52 PM" src="https://github.com/hschmidt/EnvPane/assets/97376233/f7ae6a64-f731-4b88-8995-3e9c51216f61">

**What version of EnvPane are you using. Did you download the official release or
did you build it yourself?**
v0.8, official release

**What version of OS X are you using (or attempting to use) EnvPane on?**
13.2.1

**Did you install EnvPane for the current user only or for all users? I admit,
that's a bit of a trick question.**
All users

**Did you install EnvPane as an administrative user?**
... I think? I only have one user on my computer.

**Can you provide relevant system.log messages? You can use the Console
application to get those: Hit Cmd-Space, type `Console`, hit enter (the Console
app should open), click on `system.log` on the left, click the search bar at
the top and type `Env` to filter the list. Copy and paste it below but be sure
to redact any confidential informations such as account names, IP addresses etc.**
Looks like there aren't any

**Comment by hschmidt** [comment]
I don't have a machine with 13.2.1 but I can't reproduce it on 13.4. The pane looks cut off but it is there and functional.

How did you install EnvPane? Using the [one liner](https://github.com/hschmidt/EnvPane#one-liner) or the [conventional](https://github.com/hschmidt/EnvPane#traditional-installation) method?

**Comment by jonahclarsen** [comment]
> I don't have a machine with 13.2.1 and I can't reproduce this on 13.4. The pane looks cut off but it is there and functional.
> 
> How did you install EnvPane? Using the [one liner](https://github.com/hschmidt/EnvPane#one-liner) or the [conventional](https://github.com/hschmidt/EnvPane#traditional-installation) method?

Apologies, I didn't read the instructions. I had installed using the conventional method but had selected "install for all users" rather than "this user". It's working now.
